### ISSUE TITLE
error: reference to undefined identifier 'http.MethodGet'

### ISSUE THREAD

**Issue by SLRXXX** [denverdino/aliyungo#103]
go/src/github.com/denverdino/aliyungo/common/client.go:149:20: error: reference to undefined identifier 'http.MethodGet'
  if method == http.MethodGet {
                    ^

**Comment by denverdino** [comment]
您的Go版本需要升级一下，是否可以升级到 Go 1.6以上？

**Comment by SLRXXX** [comment]
的确是go的问题，已解决，多谢！

**Comment by denverdino** [comment]
谢谢，春节快乐
