### ISSUE TITLE
SLB: can NOT get RuleId when DescribeRules

### ISSUE THREAD

**Issue by mqliang** [denverdino/aliyungo#110]
@denverdino 

根据文档：https://help.aliyun.com/document_detail/35230.html?spm=5176.doc35226.6.676.mCU5KZ， 当调用DescribeRules接口时，可以拿到所有的规则列表，但是返回的列表里只有RuleName，没有RuleId

使用场景：比如我想删除某个loadbalancer配置的所有Rules：
* 先调用DescribeRules接口拿到规则列表
* 然后调用DeleteRules接口删除规则。

问题是DescribeRules没有返回RuleId，而DeleteRules接口又需要RuleId作参数。
cc  @superxi @ddysher

**Comment by menglingwei** [comment]
@mqliang  目前我已提供的Rules相关的API。 在DescribeRules的时候，结果里是有RuleId的。目前你看到文档里没有的问题，我会反馈给相关的同学。API调用返回的格式如下：
 {
    "Rules": {
        "Rule": [
            {
                "Url": "/sample",
                "Domain": "test.com",
                "VServerGroupId": "vservergroupid",
                "RuleId": "rule-id",
                "RuleName": "rule-name"
            }
        ]
    }
}
