### ISSUE TITLE
slb的HTTPListenerType缺少VServerGroup属性

### ISSUE THREAD

**Issue by fanzy618** [denverdino/aliyungo#147]
根据 https://help.aliyun.com/document_detail/27602.html?spm=5176.doc27606.6.666.hIo2xa 的文档，为Listener配置默认的VServerGroup，除了需要VServerGroupId以外，还需要一个 VServerGroup 的参数，其类型为 slb.FlagType。
目前的API事实上无法为Listener配置VserverGroup。添加VServerGroup后，工作才正常。

**Comment by denverdino** [comment]
Fixed
