### ISSUE TITLE
type RecordType 中 TTL   类型错误

### ISSUE THREAD

**Issue by wenbc** [denverdino/aliyungo#148]
源码中，代码：
type RecordType struct {
	DomainName string
	RecordId   string
	RR         string
	Type       string
	Value      string
	TTL        int32
	Priority   int32
	Line       string
	Status     string
	Locked     bool
}

实际返回结果中，TTL为string类型，实际请求结果如下：
"DomainRecords": {
        "Record": [
            {
                "RR": "test",
                "Status": "ENABLE",
                "Value": "1.1.1.1",
                "RecordId": "342037109689856011",
                "Type": "A",
                "DomainName": "example.com",
                "Locked": false,
                "Line": "default",
                "TTL": "600"
            }
        ]
    }

**Comment by naokij** [comment]
也遇到了这问题

**Comment by menglingwei** [comment]
该问题正在确认解决中。

**Comment by wenbc** [comment]
修改一下type中ttl的类型，我本地是这么修改。不会直接修改返回吧？

**Comment by naokij** [comment]
Priority的返回类型也是string

**Comment by menglingwei** [comment]
可以使用 xxxxNew 的API。这里的API类型是正确的。

**Comment by Mr-beans** [comment]
类型错误已修复

**Comment by imlison** [comment]
带xxxNew后缀的API使用规则是怎样的，什么时候用不带New什么时候用带New的？
原先使用DescribeDomainRecordsNew一直正常，这2天报错TTL类型错误，调试输出看到TTL类型是int32

**Comment by loganhz** [comment]
怎么阿里云又给改回来了。。。。。 哎

**Comment by wenbc** [comment]
是呀，我也刚把我的程序修改了

**Comment by menglingwei** [comment]
抱歉，前段时间在和对应的开发团队在沟通。目前开发团队把类型修正了。

**Comment by loganhz** [comment]
@menglingwei 谢谢更新 ：）
