### ISSUE TITLE
在ecs包中SnapshotType 缺少 状态 字段

### ISSUE THREAD

**Issue by Hellowor** [denverdino/aliyungo#213]

**Comment by menglingwei** [comment]
@Hellowor 包里包含该字段。
请参考 https://github.com/denverdino/aliyungo/blob/master/ecs/snapshots.go 文件，如截图位置
<img width="1398" alt="snapshots" src="https://user-images.githubusercontent.com/2653769/34093868-95ed9406-e405-11e7-8417-c4f2c3c2b082.png">
