### ISSUE TITLE
关于 client Invoke  的错误: AliyunGoClientFailure Message: unexpected end of JSON input 的问题

### ISSUE THREAD

**Issue by Hellowor** [denverdino/aliyungo#214]
经测试 client.DescribeVpcs 和client.DescribeInstances 在 没有vpc 和instance时，eu-central-1 和 ap-northeast-1这两个region 的返回值是 []byte{}. 这样会导致 common/client.go Invoke方法在 308行的json.Umarshal(body,response) 中会报错 unexpected end of JSON input

**Comment by denverdino** [comment]
Checked with develop team, It should be fixed, can you try it again?
