### ISSUE TITLE
关于内容安全的服务模块

### ISSUE THREAD

**Issue by qiqizjl** [denverdino/aliyungo#226]
目前我们打算用内容安全 但是发现AliyunGo没有这个服务的模块。请问有计划添加么，或者贡献代码有什么要求么

**Comment by denverdino** [comment]
可以在 https://github.com/aliyun/alibaba-cloud-sdk-go 中提需求，官方的SDK应该会提供支持

**Comment by qiqizjl** [comment]
相当于阿里云目前官方也有Go的SDK了？ 我记得之前印象是没有的。。所以才用这个

**Comment by dinos80152** [comment]
官方終於出了 GO 版本的 SDK。本想這禮拜貢獻 CDN 新發佈的 API，剛看了官方的 SDK 已經有實作了！
有空轉換到官方的 SDK 試試，非常感謝這邊，讓人省了很多工呀！

**Comment by denverdino** [comment]
谢谢！
