### ISSUE TITLE
Can't kill & rm machine when create fail usingi aliyunecs driver

### ISSUE THREAD

**Issue by helenjie** [denverdino/aliyungo#23]
I'm trying to use docker-machine(0.5.0rc4) with aliyunecs driver and there are some issues.
First, I started to create swarm-ecs-master but there's TLS handshake timeout error: 

    $ docker-machine create --driver aliyunecs --swarm --swarm-master --swarm-discovery token://42391e615c9ee3ea568c92dddf9ee7a5 --engine-insecure-registry registry.mirrors.aliyuncs.com swarm-ecs-master 
    Creating CA: /Users/jie/.docker/machine/certs/ca.pem
    Creating client certificate: /Users/jie/.docker/machine/certs/cert.pem
    Running pre-create checks...
    Creating machine...
    Error creating machine: Error in driver during machine creation: Aliyun Error: Status Code -1: Code AliyunGoClientFailure: Message Get https://ecs.aliyuncs.com?xxxxxxxx(Some security info has been removed): net/http: TLS handshake timeout
Recreate is not allowed:

    $ docker-machine create --driver aliyunecs --swarm --swarm-master --swarm-discovery token://42391e615c9ee3ea568c92dddf9ee7a5 --engine-insecure-registry registry.mirrors.aliyuncs.com swarm-ecs-master 
    Host already exists: "swarm-ecs-master"
Then, I tried to kill it but it still got error like below:

    $ docker-machine kill swarm-ecs-master
    swarm-ecs-master | Unable to kill instance : Aliyun Error: Status Code 400: Code MissingParameter: Message The input parameter "InstanceId" that is mandatory for processing this request is not supplied.
Run *docker-machine ls* just like this:

    $ docker-machine ls
    error getting URL for host swarm-ecs-master: Aliyun Error: Status Code 400: Code MissingParameter: Message The input parameter "InstanceId" that is mandatory for processing this request is not supplied.
    error getting state for host swarm-ecs-master: Aliyun Error: Status Code 400: Code MissingParameter: Message The input parameter "InstanceId" that is mandatory for processing this request is not supplied.
    NAME               ACTIVE   DRIVER      STATE   URL   SWARM
    swarm-ecs-master   -        aliyunecs   Error         swarm-ecs-master (master)

**Comment by tg123** [comment]
try
`docker-machine rm -f ...`
and recreate one

remember to do some clean up on your aliyun console.

**Comment by helenjie** [comment]
@tg123 Thank you. I've just removed local folder ~/.docker/machine/machines/swarm-ecs-master/ to solve this problem. I think your method should be OK.

**Comment by denverdino** [comment]
@helenjie, can you recreate the issue for the TLS handshake timeout? It sounds some network configuration issue in your environment. 

Thanks
