### ISSUE TITLE
 IoT 套件 + MNS 消息队列

### ISSUE THREAD

**Issue by carl-leopard** [denverdino/aliyungo#230]
请问一下， 我目前使用的是阿里云的 IoT 套件 + MNS 消息队列 的组合进行物联网消息的传输与日志采集， 但是现在 IoT 套件设置的规则是 产品与服务端订阅（ mns 队列）一一对应的关系。 怎样做， 我才能将所有的产品的日志全部转发到 同一个 MNS 消息队列呢？你之前有过这样的经验吗？

**Comment by denverdino** [comment]
Please raise request in https://github.com/aliyun/alibaba-cloud-sdk-go

Thanks and happy spring festival!
