### ISSUE TITLE
mail_test.go:32:36: cannot use replyToAddress (type string) as type bool in field value

### ISSUE THREAD

**Issue by nim-nim** [denverdino/aliyungo#238]
Hi,

Some unit tests fail

go test -compiler gc -ldflags '-X github.com/denverdino/aliyungo/version.GitSHA=d3308649c66113b99e257dd5c92fbfdd779380c3 -extldflags '\''-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
~/build/BUILD/aliyungo-d3308649c66113b99e257dd5c92fbfdd779380c3/_build/src/github.com/denverdino/aliyungo/dm ~/build/BUILD/aliyungo-d3308649c66113b99e257dd5c92fbfdd779380c3
# github.com/denverdino/aliyungo/dm
./mail_test.go:32:36: cannot use replyToAddress (type string) as type bool in field value
FAIL	github.com/denverdino/aliyungo/dm [build failed]

**Comment by denverdino** [comment]
Fixed. Thanks
