### ISSUE TITLE
sms_test.go:15:8: client.SendSms undefined (type *Client has no field or method SendSms)

### ISSUE THREAD

**Issue by nim-nim** [denverdino/aliyungo#239]
Hi,

Some unit tests fail with the latest commit. Can you do something ?

 go test -compiler gc -ldflags '-X github.com/denverdino/aliyungo/version.GitSHA=d3308649c66113b99e257dd5c92fbfdd779380c3 -extldflags '\''-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
# github.com/denverdino/aliyungo/sms
./sms_test.go:15:8: client.SendSms undefined (type *Client has no field or method SendSms)
./sms_test.go:17:9: unknown field 'RecNum' in struct literal of type SendSmsArgs
./sms_test.go:18:15: unknown field 'ParamString' in struct literal of type SendSmsArgs
FAIL	github.com/denverdino/aliyungo/sms [build failed]

**Comment by denverdino** [comment]
Fixed. Thanks

**Comment by nim-nim** [comment]
Works for me, thanks a lot!
