### ISSUE TITLE
RDS support

### ISSUE THREAD

**Issue by Piasy** [denverdino/aliyungo#25]

**Comment by denverdino** [comment]
You are welcome for contribution.  :-)
We hope to support that in future. But there is no concrete plan in coming few months. Thanks again

**Comment by ringtail** [comment]
@Piasy can you supply the apis you need. we can develop together.

**Comment by Piasy** [comment]
@ringtail Sorry that I didn't have time last year, so I use local mysql server temporarily, but I do want to do it, and I'm glad to do it with you together, my QQ is `200842165`, can we get in touch with it?

**Comment by denverdino** [comment]
There are already some contribution for RDS support. More will be welcome. I will close this issue now
