### ISSUE TITLE
Aliyun registry version out of date

### ISSUE THREAD

**Issue by helenjie** [denverdino/aliyungo#26]
It prompted the below message after running 'docker pull mysql' successfully. In fact it behaves the same whatever I am pulling. 
  
"docker.io/library/mysql: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker."

I checked the configuration and found docker daemon is using registry.mirrors.aliyuncs.com as default registry. Is this registry maintained officially by Aliyun?

**Comment by denverdino** [comment]
registry.mirrors.aliyuncs.com is maintained officially by Aliyun, but not our team

And it is the V1 registry, the V1 registry API will be out of service by end of this year. That is why you get such warning.

The new registry will go public soon. Thanks
