### ISSUE TITLE
CS swarm cluster missing `need_slb` flag

### ISSUE THREAD

**Issue by otarabai** [denverdino/aliyungo#288]
Hi,

The Container Service cluster object doesn't support the `need_slb` flag. See: https://www.alibabacloud.com/help/doc-detail/71197.htm?spm=a2c63.p38356.a3.5.3c9d3efcKdAddN

Can you please add it?

Thanks!

**Comment by menglingwei** [comment]
the document is udpated. see [https://www.alibabacloud.com/help/zh/doc-detail/71197.htm](https://www.alibabacloud.com/help/zh/doc-detail/71197.htm)

**Comment by otarabai** [comment]
Hi @menglingwei , sorry if I was not clear. The document contains the `need_slb` flag but the go SDK does not support it. My request is to add it to the SDK. Thanks!
