### ISSUE TITLE
容器服务的KUBERNETES版本的API有实现期望吗

### ISSUE THREAD

**Issue by zkcrescent** [denverdino/aliyungo#367]

**Comment by denverdino** [comment]
It is already supported. 
@demonwy, comments pls. thx

**Comment by zkcrescent** [comment]
> It is already supported.
> @demonwy, comments pls. thx

That's awesome! Thx for your replay, I'll close this

**Comment by zkcrescent** [comment]
I find the container service package already updated 13 hours ago ,but  I could not find implementation of API `list clusters` at [official doc](https://help.aliyun.com/document_detail/90774.html?spm=a2c4g.11186623.6.1012.424a66bdlWdi0Y) ?

**Comment by menglingwei** [comment]
@zkcrescent  https://github.com/denverdino/aliyungo/blob/master/cs/clusters.go#L74

**Comment by zkcrescent** [comment]
> @zkcrescent https://github.com/denverdino/aliyungo/blob/master/cs/clusters.go#L74

I see, THX for your help
