### ISSUE TITLE
硅谷节点支持么？

### ISSUE THREAD

**Issue by ltzMaxwell** [denverdino/aliyungo#45]
如果支持的话，MACHINE_DOCKER_INSTALL_URL 和 ecs_region 怎么写？

**Comment by denverdino** [comment]
硅谷的话，MACHINE_DOCKER_INSTALL_URL 不用写的，会直接连官方网站下载Docker

ecs_region 的值是 us-west-1

谢谢！

**Comment by ltzMaxwell** [comment]
ok thx.
