### ISSUE TITLE
Will Ali provide K8S plugin for OSS & SLB

### ISSUE THREAD

**Issue by linkmancheng** [denverdino/aliyungo#62]

**Comment by denverdino** [comment]
这个可以考虑，但是现在还没有计划

**Comment by denverdino** [comment]
https://yq.aliyun.com/articles/66474

**Comment by ledzep2** [comment]
You can also try this. github.com/kubeup/kube-aliyun

**Comment by denverdino** [comment]
Pls refer https://github.com/AliyunContainerService/kubernetes

Thanks
