### ISSUE TITLE
slb could not use common.PayByBandwidth

### ISSUE THREAD

**Issue by keontang** [denverdino/aliyungo#67]
ecs use `PayByBandwidth`:
[https://help.aliyun.com/document_detail/25499.html?spm=5176.product25365.6.235.VIlqu1](https://help.aliyun.com/document_detail/25499.html?spm=5176.product25365.6.235.VIlqu1)

but slb use `paybytraffic`:
[https://help.aliyun.com/document_detail/27577.html?spm=5176.product27537.6.118.R6Bqe6](https://help.aliyun.com/document_detail/27577.html?spm=5176.product27537.6.118.R6Bqe6)

So, slb could not use `common.PayByBandwidth` in `CreateLoadBalancerArgs` struct:

```
type CreateLoadBalancerArgs struct {
    RegionId           common.Region
    LoadBalancerName   string
    AddressType        AddressType
    VSwitchId          string
    InternetChargeType common.InternetChargeType
    Bandwidth          int
    ClientToken        string
}
```

**Comment by denverdino** [comment]
Thanks for pointing it out, checking with Open API developers.
