### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by allspace** [denverdino/aliyungo#74]
Does this SDK support "append" object?

I see PutReader has parameter type "io.Reader", instead of "io.ReaderSeeker". Does it mean this method can upload data as a stream (no need wait for EOF of the data)?

**Comment by denverdino** [comment]
1. 目前不支持appendable object，请考虑使用https://github.com/aliyun/aliyun-oss-go-sdk
2. 是的它会一直从reader中读取信息并写入到对象中

**Comment by allspace** [comment]
谢谢，原来阿里云是有官方golang SDK的啊
