### ISSUE TITLE
Add support for new regions; Japan, Germany, Dubai & Australia

### ISSUE THREAD

**Issue by TamalSaha** [denverdino/aliyungo#83]
HI,
Aliyun just released support for new regions: Japan, Germany, Dubai & Australia. Can these be added to the library.

On a side note, I tried to find the region ids for Aliyun. I could not find it from there api docs. Do you mind showing how to figure this out?

Thanks.

**Comment by denverdino** [comment]
Japan: ap-northeast-1
Germany: eu-central-1
Dubai: me-east-1
Australia: ap-southeast-2

And the code is updated. Thanks

**Comment by TamalSaha** [comment]
@denverdino , can you also add these to the https://github.com/denverdino/aliyungo/issues#L23 validRegions ?

**Comment by denverdino** [comment]
Done
