### ISSUE TITLE
Is ecs default Enpoint is correct?

### ISSUE THREAD

**Issue by orangedeng** [denverdino/aliyungo#90]
I saw document (https://help.aliyun.com/document_detail/25489.html?spm=5176.doc25492.6.686.RpFcit) and it said that entry point is <ecs.aliyuncs.com>.

But i see https://github.com/denverdino/aliyungo/blob/master/ecs/client.go#L20 and it is "https://ecs-cn-hangzhou.aliyuncs.com" by default. 

It will lead to "Error creating machine: Error in driver during machine creation: Aliyun API Error: ... dial tcp 140.205.155.65:443: i/o timeout" when i create ecs instance.

**Comment by denverdino** [comment]
It should work. The https://ecs-cn-hangzhou.aliyuncs.com is the regional API endpoint.

Thanks
